openapi: 3.0.2
info:
  title: Like API
  version: "1.0"
components:
  schemas:
    article_id:
      type: string
      description: ID of the article
      format: uuid
      example: e7c8f0f0-e8e0-4e0e-b8b0-f8f8f8f8f8f8
    like_info:
      description: Information about article likes and current user
      type: object
      properties:
        like_count:
          type: integer
          format: int32
        user_liked_article:
          description: Whether the user liked the article
          oneOf:
            - type: object
              description: Information about the when the user liked the article
              properties:
                article_id:
                  type: string
                  description: ID of the article
                  format: uuid
                  example: e7c8f0f0-e8e0-4e0e-b8b0-f8f8f8f8f8f8
                user_id:
                  type: string
                  format: uuid
                  description: User ID
                  example: f0d9e6ac-18d0-4ab0-b379-d96269fb5c20
                like_date:
                  type: string
                  format: date-time
                  description: Date when the user liked the article
                  example: 2020-01-01T00:00:00Z
            - type: boolean
              example: false
  responses:
    not_found:
      description: The resource you were trying to reach is not found
      content:
        application/json:
          schema:
            type: string
            description: |
              The requested resource could not be found.
    invalid_parameters:
      description: The parameters you provided are invalid
      content:
        application/json:
          schema:
            type: object
            properties:
              errors:
                type: array
                items:
                  type: object
                  properties:
                    field:
                      type: string
                    message:
                      type: string
              type:
                type: string
                example: https://tools.ietf.org/html/rfc2616#section-10.4.7
              title:
                example: One or more validation errors ocurred.
              status:
                type: integer
                format: int32
                example: 400
              traceId:
                type: string
                example: c0a1b2c3d4e5f6a7b8c9d0e1f2
paths:
  "/articles/{article_id}/likes":
    get:
      parameters:
        - in: path
          name: article_id
          required: true
          schema:
            $ref: "#/components/schemas/article_id"
      responses:
        "200":
          description: Information found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/like_info"
        "400":
          description: Invalid parameters
          $ref: "#/components/responses/invalid_parameters"
        "404":
          description: Not Found
          $ref: "#/components/responses/not_found"
