:: Generated by: https://openapi-generator.tech
::

@echo off

dotnet restore src\LikeTrackingSystem.LikeCounter
dotnet build src\LikeTrackingSystem.LikeCounter
echo Now, run the following to start the project: dotnet run -p src\LikeTrackingSystem.LikeCounter\LikeTrackingSystem.LikeCounter.csproj --launch-profile web.
echo.
