/*
 * Like API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.IO;
using System.Reflection;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Microsoft.OpenApi.Models;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Serialization;
using LikeTrackingSystem.LikeCounter.Authentication;
using LikeTrackingSystem.LikeCounter.Filters;
using LikeTrackingSystem.LikeCounter.OpenApi;
using LikeTrackingSystem.LikeCounter.Formatters;
using LikeTrackingSystem.LikeCounter.Counter;
using LikeTrackingSystem.LikeCounter.Repository;
using Moq;
using System.Collections.Generic;
using System.Collections.Concurrent;
using System.Threading;

namespace LikeTrackingSystem.LikeCounter
{
    /// <summary>
    /// Startup
    /// </summary>
    public class Startup
    {
        /// <summary>
        /// Constructor
        /// </summary>
        /// <param name="configuration"></param>
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        /// <summary>
        /// The application configuration.
        /// </summary>
        public IConfiguration Configuration { get; }

        /// <summary>
        /// This method gets called by the runtime. Use this method to add services to the container.
        /// </summary>
        /// <param name="services"></param>
        public void ConfigureServices(IServiceCollection services)
        {

            // Add framework services.
            services
                .AddScoped<ILikeCounter, SimpleLikeCounter>()
                .AddSingleton<ILikeCountRepository>(MockLikeCountRepository)
                .AddSingleton<ILikeEventRepository>(MockLikeEventRepository)
                .AddControllers(options =>
                {
                    options.InputFormatters.Insert(0, new InputFormatterStream());
                })
                .AddNewtonsoftJson(opts =>
                {
                    opts.SerializerSettings.ContractResolver = new CamelCasePropertyNamesContractResolver();
                    opts.SerializerSettings.Converters.Add(new StringEnumConverter
                    {
                        NamingStrategy = new CamelCaseNamingStrategy()
                    });
                });

            services
                .AddSwaggerGen(c =>
                {
                    c.SwaggerDoc("1.0", new OpenApiInfo
                    {
                        Title = "Like API",
                        Description = "Like API (ASP.NET Core 5.0)",
                        TermsOfService = new Uri("https://github.com/openapitools/openapi-generator"),
                        Contact = new OpenApiContact
                        {
                            Name = "OpenAPI-Generator Contributors",
                            Url = new Uri("https://github.com/openapitools/openapi-generator"),
                            Email = ""
                        },
                        License = new OpenApiLicense
                        {
                            Name = "NoLicense",
                            Url = new Uri("http://localhost")
                        },
                        Version = "1.0",
                    });
                    c.CustomSchemaIds(type => type.FriendlyId(true));
                    c.IncludeXmlComments($"{AppContext.BaseDirectory}{Path.DirectorySeparatorChar}{Assembly.GetEntryAssembly()!.GetName().Name}.xml");

                    // Include DataAnnotation attributes on Controller Action parameters as OpenAPI validation rules (e.g required, pattern, ..)
                    // Use [ValidateModelState] on Actions to actually validate it in C# as well!
                    c.OperationFilter<GeneratePathParamsValidationFilter>();
                });
            services
                .AddSwaggerGenNewtonsoftSupport();
        }

        private ILikeEventRepository MockLikeEventRepository(IServiceProvider services)
        {
            var mock = new Mock<ILikeEventRepository>();
            var savedEvents = new ConcurrentDictionary<string, ArticleLikeEvent>();
            mock.Setup(repo => repo.AddEvent(It.IsAny<ArticleLikeEvent>()))
                .Returns<ArticleLikeEvent>((@event) =>
                {
                    var willSave = !savedEvents.ContainsKey(@event.EventHash);
                    if (willSave)
                        savedEvents.GetOrAdd(@event.EventHash, @event);
                    return willSave;
                });
            return mock.Object;
        }

        private ILikeCountRepository MockLikeCountRepository(IServiceProvider services)
        {
             var mock = new Mock<ILikeCountRepository>();

            var localCount = 0;
            mock.Setup(x => x.LikeCount(It.IsAny<string>()))
                .Returns<string>((_) => localCount);
            mock.Setup(x => x.AtomicIncrement(It.IsAny<string>()))
                .Callback<string>((_) => Interlocked.Add(ref localCount, 1))
                .Returns<string>((_) => localCount);

            return mock.Object;
        }

        /// <summary>
        /// This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        /// </summary>
        /// <param name="app"></param>
        /// <param name="env"></param>
        public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            else
            {
                app.UseHsts();
            }

            app.UseHttpsRedirection();
            app.UseDefaultFiles();
            app.UseStaticFiles();
            app.UseSwagger(c =>
                {
                    c.RouteTemplate = "openapi/{documentName}/openapi.json";
                })
                .UseSwaggerUI(c =>
                {
                    // set route prefix to openapi, e.g. http://localhost:8080/openapi/index.html
                    c.RoutePrefix = "openapi";
                    //TODO: Either use the SwaggerGen generated OpenAPI contract (generated from C# classes)
                    c.SwaggerEndpoint("/openapi/1.0/openapi.json", "Like API");

                    //TODO: Or alternatively use the original OpenAPI contract that's included in the static files
                    // c.SwaggerEndpoint("/openapi-original.json", "Like API Original");
                });
            app.UseRouting();
            app.UseEndpoints(endpoints =>
                {
                    endpoints.MapControllers();
                });
        }
    }
}
