openapi: "3.0.2"
info:
  title: Like API
  version: "1.0"

components:
  schemas:
    article_id:
      description: "ID of the article"
      $ref: "components/schemas.yaml#/components/schemas/article_id"
    like_count:
      description: "Number of likes"
      type: integer
      format: int32 
          
  responses:
    not_found:
      description: "Article not found"
      $ref: "components/responses.yaml#/components/responses/not_found"
    invalid_parameters:
      description: Invalid parameters
      $ref: "components/responses.yaml#/components/responses/invalid_parameters"
paths:
  /articles/{article_id}/likes:
    get:
      tags:
        - "Like"
      operationId: get_like_count
      parameters:
        - in: path
          name: article_id
          required: true
          schema:
            $ref: "#/components/schemas/article_id"
      responses:
        "200":
          description: Information found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/like_count"
        "400":
          description: Invalid parameters
          $ref: "#/components/responses/invalid_parameters"
        "404":
          description: Not Found
          $ref: "#/components/responses/not_found"
