/*
 * Like API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Swashbuckle.AspNetCore.Annotations;
using Swashbuckle.AspNetCore.SwaggerGen;
using Newtonsoft.Json;
using LikeTrackingSystem.LikeCounter.Attributes;
using LikeTrackingSystem.LikeCounter.Models;
using LikeTrackingSystem.LikeCounter.Counter;
using LikeTrackingSystem.Framework.Logging;

namespace LikeTrackingSystem.LikeCounter.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public class LikeApiController : ControllerBase
    {

        ILikeCounter _likeCounter;

        ILogBook _log;

        public LikeApiController(ILikeCounter likeCounter, ILogBook? log = null)
        {
            _likeCounter = likeCounter;
            _log = log ?? Log.Null;
        }



        /// <summary>
        /// Get likes for a article
        /// </summary>
        /// <param name="articleId"></param>
        /// <response code="200">Information found</response>
        /// <response code="400">The parameters you provided are invalid</response>
        /// <response code="404">The resource you were trying to reach is not found</response>
        [HttpGet]
        [Route("/articles/{article_id}/likes")]
        [ValidateModelState]
        [SwaggerOperation("GetLikeCount")]
        [SwaggerResponse(statusCode: 200, type: typeof(int), description: "Information found")]
        [SwaggerResponse(statusCode: 400, type: typeof(InlineResponse400), description: "The parameters you provided are invalid")]
        [SwaggerResponse(statusCode: 404, type: typeof(string), description: "The resource you were trying to reach is not found")]
        public virtual IActionResult GetLikeCount([FromRoute (Name = "article_id")][Required]Guid articleId)
        { 

            try
            {
                _log.WithArticle(articleId.ToString()).Information("Get likes info");
                var count = _likeCounter.LikesFor(articleId.ToString());

                if (count is null)
                {
                    _log.Warning("Article not found");
                    return NotFound($"No article found for {articleId}");
                }

                return Ok(count);
            }
            catch (Exception ex)
            {
                _log.Error("Error occurred when trying to like article", ex);
                return StatusCode(StatusCodes.Status500InternalServerError, ex.Message);
            }
        }
    }
}
